name: smash-with-power
base: core22
version: '0.1.0'
summary: <PlaceHolderShortDesc>
description: |
  <PlaceHolderLongDesc>

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  smash-with-power:
    command: smash-with-power
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - network
      - opengl
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - unity7
    desktop: others/snap/gui/smash-with-power.desktop

parts:
  smash-with-power:
    plugin: dump
    source: ./builds/
    source-type: local
    stage-packages:
      - libglu1-mesa
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxi6
      - libpulse0
    override-build: |
      snapcraftctl build
      chmod +x $SNAPCRAFT_PART_INSTALL/smash-with-power

layout:
  /usr/share/smash-with-power:
    bind: $SNAP/usr/share/smash-with-power
